travis:
  secure:
    BINSTAR_TOKEN: mlMK9yxed/RHQL9pQS6h6lISD3LFOfl+D1zuQL8xiiReS+IbE12Wy6kPknepOksZWmirhuB8Xxo7MkIzYEOIINdTEx0iW4339IvGYSz90AjASOEWUrYKsEsfI2EuDbAJtWGzaLt5fBQFzLvSkdBnI3kf1Bm+9GhrM5w0gEvgh37ZS4/uFdW3PdKI3SUfWz/q7xaf1QN4y21PF2SVNIdThSGHn7byhnlLaw5LjkE3VrN31WNIoPnQ3aCslMFhCi1qhziyUt1LH56Cs8cvg094RbMQAUCvbHHRUEd4nyk/OubdcFyHTgDMSrpE0buISz+ZU2ZDUkR7zkI8+oF9P9grhx9DjNGWljTMExu+oS+kbAzQw2hdqVOQPheldBuMzjm35itcT5H6knkQPL0tsHw50IB1SaShgsTozdPt8ud4taSIIQuv3D0WIQcewGWMcpQ019GM9+tQd+v5L6ip7OS8v8xvUlpU25h6LdXKfGqkQ6i5L53GEpbNaD3WebwDZ3KD6BEezIFZlctoVvs0sRGfNrXwkTqgbeBOhEf8qjRf12TGvb5eBAOegJ+ZL3AVQuOv5C28X8wsJykms3eXSDTZxm+XY219nN4qtTRuhSKIDAWpTjasU7TZOv8ksxxrrIHNN7JbFV0y+c98r1fKB5KJB1U3RgGOoUr0VXK8aNyNcU4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
